# Generated by Django 5.2.4 on 2025-08-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("buying", "Buying Inquiry"),
                            ("selling", "Selling Inquiry"),
                            ("renting", "Renting Inquiry"),
                            ("investment", "Investment Inquiry"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("follow_up", "Follow Up"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Contact Inquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
